### ISSUE TITLE
Document how to install lilv python dependency

### ISSUE THREAD

**Issue by jhordies** [ajboni/calvo#42]
Hello,
The app seems great but I can't get it to run.
I installed all the dependencies, I'm no expert in python, it seems that I'm still missing the lilv python bindings.
How did you get them to work?
Thanks

**Comment by ajboni** [comment]
Hi!! I think it comes with lilv package. Do you have it on your system?
https://github.com/ajboni/calvo-cli-tools/tree/4bdf43e37a6e7c21471c5b519f31ef4e906b005e#lv2

**Comment by jhordies** [comment]
Unfortunately it doesn't.
I installed lilv tools and lilv dev, I have the command lines tools
working. But python complains the module is missing.
I'm using an Ubuntu based distribution friendly core ( nano pi neo 3)

**Comment by ajboni** [comment]
Oh, I Will try tonight in arch  . I remember back then that I had to compile serd and sord and lilv to make lilv work on Ubuntu. But it was a few years ago. Does lv2ls or similar tools work?

**Comment by ajboni** [comment]
I tried and in my case I was missing the `python-jack-client` package, added it as a dependency in readme. Maybe that is what you are missing. `sudo pacman -S python-jack-client   `. Also found a typo which was trying to use the upstream library.

**Comment by jhordies** [comment]
Thanks a lot for your investigations.
Unfortunately it still doesn't work for me.

***@***.***:~# sudo apt-get install python-jack-client
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python-jack-client
***@***.***:~# sudo apt-get install python3-jack-client
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer
required:
  xserver-xorg-video-nouveau xserver-xorg-video-vesa
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  python3-cffi python3-ply python3-pycparser
Suggested packages:
  python3-numpy python-ply-doc
The following NEW packages will be installed:
  python3-cffi python3-jack-client python3-ply python3-pycparser
0 upgraded, 4 newly installed, 0 to remove and 302 not upgraded.
Need to get 223 kB of archives.
After this operation, 1392 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64
python3-ply all 3.11-3ubuntu0.1 [46.3 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal/main arm64
python3-pycparser all 2.19-1ubuntu1 [71.0 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 python3-cffi
all 1.14.0-1build1 [70.3 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal/universe arm64
python3-jack-client all 0.5.0-1 [35.0 kB]
Fetched 223 kB in 0s (1053 kB/s)
Selecting previously unselected package python3-ply.
(Reading database ... 67115 files and directories currently installed.)
Preparing to unpack .../python3-ply_3.11-3ubuntu0.1_all.deb ...
Unpacking python3-ply (3.11-3ubuntu0.1) ...
Selecting previously unselected package python3-pycparser.
Preparing to unpack .../python3-pycparser_2.19-1ubuntu1_all.deb ...
Unpacking python3-pycparser (2.19-1ubuntu1) ...
Selecting previously unselected package python3-cffi.
Preparing to unpack .../python3-cffi_1.14.0-1build1_all.deb ...
Unpacking python3-cffi (1.14.0-1build1) ...
Selecting previously unselected package python3-jack-client.
Preparing to unpack .../python3-jack-client_0.5.0-1_all.deb ...
Unpacking python3-jack-client (0.5.0-1) ...
Setting up python3-ply (3.11-3ubuntu0.1) ...
Setting up python3-pycparser (2.19-1ubuntu1) ...
Setting up python3-cffi (1.14.0-1build1) ...
Setting up python3-jack-client (0.5.0-1) ...
Processing triggers for man-db (2.9.1-1) ...
***@***.***:~# cd calvo/calvo/
***@***.***:~/calvo/calvo# npm start

> ***@***.*** start /root/calvo/calvo
> node src/app.js

Building plugins cache, this might take a while, please wait...
Traceback (most recent call last):
  File "./py/calvo_cli_tools/lv2/grep.py", line 32, in <module>
    import lilv
ModuleNotFoundError: No module named 'lilv'
{ Error: Command failed: python3 ./py/calvo_cli_tools/lv2/grep.py -c --json
.
Traceback (most recent call last):
  File "./py/calvo_cli_tools/lv2/grep.py", line 32, in <module>
    import lilv
ModuleNotFoundError: No module named 'lilv'

    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at grep (/root/calvo/calvo/src/lv2.js:62:23)
    at buildPluginCache (/root/calvo/calvo/src/lv2.js:37:21)
    at Object.init (/root/calvo/calvo/src/lv2.js:24:5)
    at Object.<anonymous> (/root/calvo/calvo/src/app.js:20:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
  status: 1,
  signal: null,
  output:
   [ null,
     '',
     'Traceback (most recent call last):\n  File
"./py/calvo_cli_tools/lv2/grep.py", line 32, in <module>\n    import
lilv\nModuleNotFoundError: No module named \'lilv\'\n' ],
  pid: 25931,
  stdout: '',
  stderr:
   'Traceback (most recent call last):\n  File
"./py/calvo_cli_tools/lv2/grep.py", line 32, in <module>\n    import
lilv\nModuleNotFoundError: No module named \'lilv\'\n' }
TypeError: Found non-callable @@iterator
    at buildPluginCache (/root/calvo/calvo/src/lv2.js:39:25)
    at Object.init (/root/calvo/calvo/src/lv2.js:24:5)
    at Object.<anonymous> (/root/calvo/calvo/src/app.js:20:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
control open "hw:0" (No such file or directory)
control open "hw:0" (No such file or directory)
control open "hw:0" (No such file or directory)
ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card
ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to
capture-only mode
JackTemporaryException : now quits...
control open "hw:0" (No such file or directory)
control open "hw:0" (No such file or directory)
Cannot initialize driver
JackServer::Open failed with -1
Failed to open server
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping
unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping
unlock
Could not create JACK client: Error initializing "calvo-poll": <jack.Status
0x11: ***@***.***


Here are some tests of lilv..
***@***.***:~/calvo/calvo# lv2
lv2-grep                 lv2-plugin-uris          lv2bench
lv2-list-plugin-presets  lv2_validate             lv2info
lv2-plugin-info          lv2apply                 lv2ls
***@***.***:~/calvo/calvo# lv2ls
http://lv2plug.in/plugins/eg-amp
http://lv2plug.in/plugins/eg-fifths
http://lv2plug.in/plugins/eg-metro
http://lv2plug.in/plugins/eg-midigate
http://lv2plug.in/plugins/eg-params
http://lv2plug.in/plugins/eg-scope#Mono
http://lv2plug.in/plugins/eg-scope#Stereo
***@***.***:~/calvo/calvo# lv2-grep
Traceback (most recent call last):
  File "/usr/local/bin/lv2-grep", line 5, in <module>
    from jackaudiotools.lv2.grep import main
  File "/usr/local/lib/python3.8/dist-packages/jackaudiotools/lv2/grep.py",
line 10, in <module>
    import lilv
ModuleNotFoundError: No module named 'lilv'

**Comment by ajboni** [comment]
Thanks, seems like python bindings for lilv are not installed , I don't know much about ubuntu to give you a proper answer unfortunately :(

**Comment by madorian** [comment]
Has this project been packaged for any distro? I'm trying to make a nix file for it.

**Comment by ajboni** [comment]
> Has this project been packaged for any distro? I'm trying to make a nix file for it.

Hi, no unfortunately not and I lost track of the deps needed, just tried it in arch and got it to run but cannot add plugins.  (updated readme with python-lilv dependency. might need to do some research and update docs . If you find anything please let me know!
